[build]
  base = "/"
  publish = "public"
  command = "npm install && hexo generate --draft false"

[build.environment]
  NODE_VERSION = "22.11"

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true