[build]
  publish = "public"
  command = "hexo generate"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true